<article class="article_holder">
    <div class="home_top3owl_carousel clearfix">
        <div class="top3owl-carousel">
            <div class="item">
                <div class="top3owl_holder"><img alt="fresh new look" src="<?php echo $this->getSkinUrl('images/fresh_new_look.jpg');?>" />
                    <p class="top3owl_link"><a href="#">TAKE A TOUR</a></p>
                </div>
            </div>
            <div class="item">
                <div class="top3owl_holder"><img alt="stop smoking start vaping" src="<?php echo $this->getSkinUrl('images/stop_smoking_start_vaping.jpg');?>" />
                    <p class="top3owl_link"><a href="#">LEARN MORE</a></p>
                </div>
            </div>
            <div class="item">
                <div class="top3owl_holder"><img alt="discover new tastes" src="<?php echo $this->getSkinUrl('images/discover_new_tastes.jpg');?>" />
                    <p class="top3owl_link"><a href="#">DISCOVER THEM</a></p>
                </div>
            </div>
            <div class="item">
                <div class="top3owl_holder"><img alt="fresh new look" src="<?php echo $this->getSkinUrl('images/fresh_new_look.jpg');?>" />
                    <p class="top3owl_link"><a href="#">TAKE A TOUR</a></p>
                </div>
            </div>
            <div class="item">
                <div class="top3owl_holder"><img alt="stop smoking start vaping" src="<?php echo $this->getSkinUrl('images/stop_smoking_start_vaping.jpg');?>" />
                    <p class="top3owl_link"><a href="#">LEARN MORE</a></p>
                </div>
            </div>
            <div class="item">
                <div class="top3owl_holder"><img alt="discover new tastes" src="<?php echo $this->getSkinUrl('images/discover_new_tastes.jpg');?>" />
                    <p class="top3owl_link"><a href="#">DISCOVER THEM</a></p>
                </div>
            </div>
            <div class="item">
                <div class="top3owl_holder"><img alt="discover new tastes" src="<?php echo $this->getSkinUrl('images/discover_new_tastes.jpg');?>" />
                    <p class="top3owl_link"><a href="#">DISCOVER THEM</a></p>
                </div>
            </div>
            <div class="item">
                <div class="top3owl_holder"><img alt="fresh new look" src="<?php echo $this->getSkinUrl('images/fresh_new_look.jpg');?>" />
                    <p class="top3owl_link"><a href="#">TAKE A TOUR</a></p>
                </div>
            </div>
            <div class="item">
                <div class="top3owl_holder"><img alt="stop smoking start vaping" src="<?php echo $this->getSkinUrl('images/stop_smoking_start_vaping.jpg');?>" />
                    <p class="top3owl_link"><a href="#">LEARN MORE</a></p>
                </div>
            </div>
            <div class="item">
                <div class="top3owl_holder"><img alt="discover new tastes" src="<?php echo $this->getSkinUrl('images/discover_new_tastes.jpg');?>" />
                    <p class="top3owl_link"><a href="#">DISCOVER THEM</a></p>
                </div>
            </div>
        </div>
    </div>
    <div class="quickpopularaid clearfix">
        <div class="quickpopularaid_outer">
            <div class="quickpopularaid_hloder quickpopularaidleft_hloder">
                <div class="quickpopularaid_inn">
                    <h2><span>QUICK</span> ACCESS</h2>
                    <div class="quick6_hloder clearfix">
                        <ul class="quick6_part1">
                            <li><a class="quick6_hloder_inn" href="javascript:void(0)"> <img class="quick6_link_img" alt="todays_deals" src="<?php echo $this->getSkinUrl('images/todays_deals.png');?>" /> <img class="quick6_hover_img" alt="todays_deals" src="<?php echo $this->getSkinUrl('images/todays_deals_hover.png');?>" /> <img class="quick6_activeout_img" alt="todays_deals" src="<?php echo $this->getSkinUrl('images/todays_deals_activeout.png');?>" /></a>
                                <div class="ribbon_div"><span>TODAY&rsquo;s</span>DEALS</div>
                            </li>
                            <li><a class="quick6_hloder_inn" onclick="smoothScroll(document.getElementById('topeliquiedsactive'))" href="javascript:void(0)"> <img class="quick6_link_img" alt="top_eliquieds" src="<?php echo $this->getSkinUrl('images/top_eliquieds.png');?>" /> <img class="quick6_hover_img" alt="top_eliquieds" src="<?php echo $this->getSkinUrl('images/top_eliquieds_hover.png');?>" /> <img class="quick6_activeout_img" alt="top_eliquieds" src="<?php echo $this->getSkinUrl('images/top_eliquieds_activeout.png');?>" /></a>
                                <div class="ribbon_div"><span>TOP</span> E-LIQUID</div>
                            </li>
                            <li class="last"><a class="quick6_hloder_inn" onclick="smoothScroll(document.getElementById('topdevicesactive'))" href="javascript:void(0)"> <img class="quick6_link_img" alt="top_devices" src="<?php echo $this->getSkinUrl('images/top_devices.png');?>" /> <img class="quick6_hover_img" alt="top_devices" src="<?php echo $this->getSkinUrl('images/top_devices_hover.png');?>" /> <img class="quick6_activeout_img" alt="top_devices" src="<?php echo $this->getSkinUrl('images/top_devices_activeout.png');?>" /></a>
                                <div class="ribbon_div"><span>TOP</span> DEVICES</div>
                            </li>
                        </ul>
                        <ul class="quick6_part2">
                            <li><a class="quick6_hloder_inn" onclick="smoothScroll(document.getElementById('newarrivalsactive'))" href="javascript:void(0)"> <img class="quick6_link_img" alt="new_arrivals" src="<?php echo $this->getSkinUrl('images/new_arrivals.png');?>" /> <img class="quick6_hover_img" alt="new_arrivals" src="<?php echo $this->getSkinUrl('images/new_arrivals_hover.png');?>" /> <img class="quick6_activeout_img" alt="new_arrivals" src="<?php echo $this->getSkinUrl('images/new_arrivals_activeout.png');?>" /></a>
                                <div class="ribbon_div"><span>NEW</span>ARRIVALS</div>
                            </li>
                            <li><a class="quick6_hloder_inn" onclick="smoothScroll(document.getElementById('featuredproductsactive'))" href="javascript:void(0)"> <img class="quick6_link_img" alt="featured_products" src="<?php echo $this->getSkinUrl('images/featured_products.png');?>" /> <img class="quick6_hover_img" alt="featured_products" src="<?php echo $this->getSkinUrl('images/featured_products_hover.png');?>" /> <img class="quick6_activeout_img" alt="featured_products" src="<?php echo $this->getSkinUrl('images/featured_products_activeout.png');?>" /></a>
                                <div class="ribbon_div"><span>FEATURED</span>PRODUCTS</div>
                            </li>
                            <li class="last active"><a class="quick6_hloder_inn" onclick="smoothScroll(document.getElementById('clearanceactive'))" href="javascript:void(0)"> <img class="quick6_link_img" alt="clearance" src="<?php echo $this->getSkinUrl('images/clearance.png');?>" /> <img class="quick6_hover_img" alt="clearance" src="<?php echo $this->getSkinUrl('images/clearance_hover.png');?>" /> <img class="quick6_activeout_img" alt="clearance" src="<?php echo $this->getSkinUrl('images/clearance_activeout.png');?>" /></a>
                                <div class="ribbon_div singleline"><span>CLEARANCE</span></div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="quickpopularaid_hloder2"><!-- popularaid -->
                <div id="popularaid" class="quickpopularaid_mainpart" style="display: block;">
                    <div class="quickpopularaid_hloder quickpopularaidmiddle_hloder">
                        <div class="quickpopularaid_inn">
                            <h2><span>POPULAR</span> CATEGORIES</h2>
                            <div class="popular6_hloder clearfix">
                                <ul class="popular6_part1">
                                    <li><a class="popular6_hloder_inn" href="#"> <img class="popular6_link_img" alt="tanks" src="<?php echo $this->getSkinUrl('images/tanks.png');?>" /> <img class="popular6_hover_img" alt="tanks" src="<?php echo $this->getSkinUrl('images/tanks_hover.png');?>" /></a>
                                        <div class="ribbon_div singleline"><span>TANKS</span></div>
                                    </li>
                                    <li><a class="popular6_hloder_inn" href="#"> <img class="popular6_link_img" alt="rdasrtas" src="<?php echo $this->getSkinUrl('images/rdasrtas.png');?>" /> <img class="popular6_hover_img" alt="rdasrtas" src="<?php echo $this->getSkinUrl('images/rdasrtas_hover.png');?>" /></a>
                                        <div class="ribbon_div"><span>RDAs</span>RDTAs</div>
                                    </li>
                                    <li class="last"><a class="popular6_hloder_inn" href="#"> <img class="popular6_link_img" alt="coilbuilderzone" src="<?php echo $this->getSkinUrl('images/coilbuilderzone.png');?>" /> <img class="popular6_hover_img" alt="coilbuilderzone" src="<?php echo $this->getSkinUrl('images/coilbuilderzone_hover.png');?>" /></a>
                                        <div class="ribbon_div"><span>COIL BUILDER</span>ZONE</div>
                                    </li>
                                </ul>
                                <ul class="popular6_part2">
                                    <li><a class="popular6_hloder_inn" href="#"> <img class="popular6_link_img" alt="eliquidsi" src="<?php echo $this->getSkinUrl('images/eliquidsicon.png');?>" /> <img class="popular6_hover_img" alt="eliquidsicon" src="<?php echo $this->getSkinUrl('images/eliquidsicon_hover.png');?>" /></a>
                                        <div class="ribbon_div singleline"><span>E-LIQUIDS</span></div>
                                    </li>
                                    <li><a class="popular6_hloder_inn" href="#"> <img class="popular6_link_img" alt="modes" src="<?php echo $this->getSkinUrl('images/modes.png');?>" /> <img class="popular6_hover_img" alt="modes" src="<?php echo $this->getSkinUrl('images/modes_hover.png');?>" /></a>
                                        <div class="ribbon_div singleline"><span>MODS</span></div>
                                    </li>
                                    <li class="last"><a class="popular6_hloder_inn" href="#"> <img class="popular6_link_img" alt="starterkits" src="<?php echo $this->getSkinUrl('images/starterkits.png');?>" /> <img class="popular6_hover_img" alt="starterkits" src="<?php echo $this->getSkinUrl('images/starterkits_hover.png');?>" /></a>
                                        <div class="ribbon_div clearance_div"><span>STARTER</span>KITS</div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="quickpopularaid_hloder quickpopularaidright_hloder">
                        <div class="quickpopularaid_inn">
                            <h2>FIRST <span>AID</span></h2>
                            <div class="aid2_hloder clearfix">
                                <ul class="aid2_part1">
                                    <li><a class="aid2_hloder_inn" href="new-to-vaping.html"> <img class="aid2_link_img" alt="new_to_vaping" src="<?php echo $this->getSkinUrl('images/new_to_vaping.png');?>" /> <img class="aid2_hover_img" alt="new_to_vaping" src="<?php echo $this->getSkinUrl('images/new_to_vaping_hover.png');?>" /></a>
                                        <div class="ribbon_div"><span>START</span> HERE</div>
                                    </li>
                                    <li><a class="aid2_hloder_inn" href="#"> <img class="aid2_link_img" alt="vape_kit_builder" src="<?php echo $this->getSkinUrl('images/vape_kit_builder.png');?>" /> <img class="aid2_hover_img" alt="vape_kit_builder" src="<?php echo $this->getSkinUrl('images/vape_kit_builder_hover.png');?>" /></a>
                                        <div class="ribbon_div"><span>ADVANCED</span>USERS</div>
                                    </li>
                                </ul>
                                <ul class="aid2_part2">
                                    <li><a class="aid2_hloder_inn" href="#"> <img class="aid2_link_img" alt="vape_product_advisor" src="<?php echo $this->getSkinUrl('images/vape_product_advisor.png');?>" /> <img class="aid2_hover_img" alt="vape_product_advisor" src="<?php echo $this->getSkinUrl('images/vape_product_advisor_hover.png');?>" /> </a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- todaysdealsactive -->
                <div id="todaysdealsactive" class="quickpopularaid_mainpart" style="display: none;">
                    <div class="quickpopularaid_hloder quickpopularaidmiddle_hloder">
                        <div class="quickpopularaid_inn coverbg" style="background-image: url('<?php echo $this->getSkinUrl('images/e_cig_products_bg.png');?>');">
                            <h2>TODAY'S <span>Product</span> DEAL</h2>
                            <div class="popular6_hloder clearfix">
                                <div class="todaysdealsactive_product">
                                    <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_cig_accessories.png');?>" /></a></div>
                                    <div class="todaysdealsactive_title clearfix">
                                        <h3><a href="#">E-cig Product</a></h3>
                                        <div class="rating_star">(55)</div>
                                    </div>
                                    <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled.</div>
                                    <div class="todaysdealsactive_price clearfix">
                                        <ul>
                                            <li>Original Price <span><sub>$</sub>70.00</span></li>
                                            <li class="middle_price">50% OFF</li>
                                            <li class="deal_price">Deal Price <span><sub>$</sub>35.00</span></li>
                                        </ul>
                                    </div>
                                    <div class="todaysdealsactive_button clearfix"><a class="select_option" href="#">Select Options</a> <a class="remindme_tobuy" href="#">Remind me to buy</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="quickpopularaid_hloder quickpopularaidright_hloder">
                        <div class="quickpopularaid_inn coverbg" style="background-image: url('<?php echo $this->getSkinUrl('images/e_liquid_menu_bg.png');?>');">
                            <h2>TODAY'S <span>E-liquid</span> DEAL</h2>
                            <div class="popular6_hloder clearfix">
                                <div class="todaysdealsactive_product">
                                    <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_liquidproduct.png');?>" /></a></div>
                                    <div class="todaysdealsactive_title clearfix">
                                        <h3><a href="#">E-cig Product</a></h3>
                                        <div class="rating_star">(55)</div>
                                    </div>
                                    <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                    <div class="todaysdealsactive_price clearfix">
                                        <ul>
                                            <li>Original Price <span><sub>$</sub>70.00</span></li>
                                            <li class="middle_price">50% OFF</li>
                                            <li class="deal_price">Deal Price <span><sub>$</sub>35.00</span></li>
                                        </ul>
                                    </div>
                                    <div class="todaysdealsactive_button clearfix"><a class="select_option" href="#">Select Options</a> <a class="remindme_tobuy" href="#">Remind me to buy</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- topeliquiedsactive -->
                <div id="topeliquiedsactive" class="quickpopularaid_mainpart" style="display: none;">
                    <div class="quickpopularaid_hloder quickpopularaid_oneline quickpopularaidright_hloder">
                        <div class="quickpopularaid_inn">
                            <h2>Top <span>E-liquieds</span></h2>
                            <div class="topdeals_part clearfix">
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_liquidsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_liquidsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_liquidsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_liquidsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_liquidsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_liquidsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_liquidsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_liquidsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_liquidsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_liquidsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- topeliquiedsactive -->
                <div id="topdevicesactive" class="quickpopularaid_mainpart" style="display: none;">
                    <div class="quickpopularaid_hloder quickpopularaid_oneline quickpopularaidright_hloder">
                        <div class="quickpopularaid_inn">
                            <h2>Top <span>Devices</span></h2>
                            <div class="topdeals_part clearfix">
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e-cigsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e-cigsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e-cigsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e-cigsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e-cigsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e-cigsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e-cigsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e-cigsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e-cigsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                                <div class="topdeals_holder">
                                    <div class="topdeals_holder_inn">
                                        <div class="topdeals_title"><span>Brand</span> Product Name</div>
                                        <div class="topdeals_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e-cigsmall.png');?>" /></div>
                                        <div class="topdeals_likeshare clearfix">&nbsp;</div>
                                        <div class="topdeals_pricerating clearfix">
                                            <div class="topdeals_price">$9999.00</div>
                                            <div class="topdeals_rating">&nbsp;</div>
                                        </div>
                                        <div class="topdeals_addcart clearfix"><a href="#">Add to cart</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- topeliquiedsactive -->
                <div id="newarrivalsactive" class="quickpopularaid_mainpart" style="display: none;">
                    <div class="newarrivalsactive_carousel">
                        <div class="newarrivals-carousel">
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg">
                                        <h2><span>Limited</span> Quantity</h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/rda.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg">
                                        <h2><span>Japanese</span> Import</h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/mods.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg">
                                        <h2><span>New</span> Price</h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/eliquid.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg">
                                        <h2><span>Limited</span> Quantity</h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/rda.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg">
                                        <h2><span>Japanese</span> Import</h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/mods.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg">
                                        <h2><span>New</span> Price</h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/eliquid.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg">
                                        <h2><span>Limited</span> Quantity</h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/rda.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg">
                                        <h2><span>Japanese</span> Import</h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/mods.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg">
                                        <h2><span>New</span> Price</h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/eliquid.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- featuredproductsactive -->
                <div id="featuredproductsactive" class="quickpopularaid_mainpart" style="display: none;">
                    <div class="featuredproductsactive_carousel">
                        <div class="featuredproducts-carousel">
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg" style="background-image: url('<?php echo $this->getSkinUrl('images/e_liquid_menu_bg.png');?>');">
                                        <h2><span>Maximum</span> Vape</h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/e-cig_small.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg" style="background-image: url('<?php echo $this->getSkinUrl('images/e_cig_products_bg.png');?>');">
                                        <h2><span>First</span> of <span>Seven</span></h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_cig_small.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg" style="background-image: url('<?php echo $this->getSkinUrl('images/e_liquid_menu_bg.png');?>');">
                                        <h2><span>2016</span> Edition</h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_liquid_small.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg" style="background-image: url('<?php echo $this->getSkinUrl('images/e_liquid_menu_bg.png');?>');">
                                        <h2><span>Maximum</span> Vape</h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/e-cig_small.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg" style="background-image: url('<?php echo $this->getSkinUrl('images/e_cig_products_bg.png');?>');">
                                        <h2><span>First</span> of <span>Seven</span></h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_cig_small.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg" style="background-image: url('<?php echo $this->getSkinUrl('images/e_liquid_menu_bg.png');?>');">
                                        <h2><span>2016</span> Edition</h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_liquid_small.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg" style="background-image: url('<?php echo $this->getSkinUrl('images/e_liquid_menu_bg.png');?>');">
                                        <h2><span>Maximum</span> Vape</h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/e-cig_small.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg" style="background-image: url('<?php echo $this->getSkinUrl('images/e_cig_products_bg.png');?>');">
                                        <h2><span>First</span> of <span>Seven</span></h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_cig_small.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="item_carousel_holder">
                                    <div class="quickpopularaid_inn coverbg" style="background-image: url('<?php echo $this->getSkinUrl('images/e_liquid_menu_bg.png');?>');">
                                        <h2><span>2016</span> Edition</h2>
                                        <div class="popular6_hloder clearfix">
                                            <div class="todaysdealsactive_product">
                                                <div class="todaysdealsactive_img"><a href="#"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_liquid_small.png');?>" /></a></div>
                                                <div class="todaysdealsactive_title clearfix">
                                                    <h3><a href="#">E-cig Product</a></h3>
                                                    <div class="rating_star">(55)</div>
                                                </div>
                                                <div class="todaysdealsactive_text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</div>
                                                <div class="todaysdealsactive_button clearfix">
                                                    <div class="pull-left">$99999.00</div>
                                                    <div class="pull-right"><a class="select_option" href="#"> &nbsp; &nbsp; BUY NOW &nbsp; &nbsp; </a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- clearanceactive -->
                <div id="clearanceactive" class="quickpopularaid_mainpart" style="display: none;">
                    <div class="quickpopularaid_hloder quickpopularaidmiddle_hloder">
                        <div class="quickpopularaid_inn">
                            <h2><span>POPULAR</span> CATEGORIES</h2>
                            <div class="popular6_hloder clearfix">
                                <ul class="popular6_part1">
                                    <li><a class="popular6_hloder_inn" href="#"> <img class="popular6_link_img" alt="tanks" src="<?php echo $this->getSkinUrl('images/tanks.png');?>" /> <img class="popular6_hover_img" alt="tanks" src="<?php echo $this->getSkinUrl('images/tanks_hover.png');?>" /></a>
                                        <div class="ribbon_div singleline"><span>TANKS</span></div>
                                    </li>
                                    <li><a class="popular6_hloder_inn" href="#"> <img class="popular6_link_img" alt="rdasrtas" src="<?php echo $this->getSkinUrl('images/rdasrtas.png');?>" /> <img class="popular6_hover_img" alt="rdasrtas" src="<?php echo $this->getSkinUrl('images/rdasrtas_hover.png');?>" /></a>
                                        <div class="ribbon_div"><span>RDAs</span>RDTAs</div>
                                    </li>
                                    <li class="last"><a class="popular6_hloder_inn" href="#"> <img class="popular6_link_img" alt="coilbuilderzone" src="<?php echo $this->getSkinUrl('images/coilbuilderzone.png');?>" /> <img class="popular6_hover_img" alt="coilbuilderzone" src="<?php echo $this->getSkinUrl('images/coilbuilderzone_hover.png');?>" /></a>
                                        <div class="ribbon_div"><span>COIL BUILDER</span>ZONE</div>
                                    </li>
                                </ul>
                                <ul class="popular6_part2">
                                    <li><a class="popular6_hloder_inn" href="#"> <img class="popular6_link_img" alt="eliquidsi" src="<?php echo $this->getSkinUrl('images/eliquidsicon.png');?>" /> <img class="popular6_hover_img" alt="eliquidsicon" src="<?php echo $this->getSkinUrl('images/eliquidsicon_hover.png');?>" /></a>
                                        <div class="ribbon_div singleline">E-LIQUIDS</div>
                                    </li>
                                    <li><a class="popular6_hloder_inn" href="#"> <img class="popular6_link_img" alt="modes" src="<?php echo $this->getSkinUrl('images/modes.png');?>" /> <img class="popular6_hover_img" alt="modes" src="<?php echo $this->getSkinUrl('images/modes_hover.png');?>" /></a>
                                        <div class="ribbon_div singleline"><span>MODS</span></div>
                                    </li>
                                    <li class="last"><a class="popular6_hloder_inn" href="#"> <img class="popular6_link_img" alt="starterkits" src="<?php echo $this->getSkinUrl('images/starterkits.png');?>" /> <img class="popular6_hover_img" alt="starterkits" src="<?php echo $this->getSkinUrl('images/starterkits_hover.png');?>" /></a>
                                        <div class="ribbon_div clearance_div"><span>STARTER</span>KITS</div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="quickpopularaid_hloder quickpopularaidright_hloder">
                        <div class="quickpopularaid_inn">
                            <h2>FIRST <span>AID</span></h2>
                            <div class="aid2_hloder clearfix">
                                <ul class="aid2_part1">
                                    <li><a class="aid2_hloder_inn" href="#"> <img class="aid2_link_img" alt="new_to_vaping" src="<?php echo $this->getSkinUrl('images/new_to_vaping.png');?>" /> <img class="aid2_hover_img" alt="new_to_vaping" src="<?php echo $this->getSkinUrl('images/new_to_vaping_hover.png');?>" /></a>
                                        <div class="ribbon_div"><span>START</span> HERE</div>
                                    </li>
                                    <li><a class="aid2_hloder_inn" href="#"> <img class="aid2_link_img" alt="vape_kit_builder" src="<?php echo $this->getSkinUrl('images/vape_kit_builder.png');?>" /> <img class="aid2_hover_img" alt="vape_kit_builder" src="<?php echo $this->getSkinUrl('images/vape_kit_builder_hover.png');?>" /></a>
                                        <div class="ribbon_div"><span>ADVANCED</span>USERS</div>
                                    </li>
                                </ul>
                                <ul class="aid2_part2">
                                    <li><a class="aid2_hloder_inn" href="#"> <img class="aid2_link_img" alt="vape_product_advisor" src="<?php echo $this->getSkinUrl('images/vape_product_advisor.png');?>" /> <img class="aid2_hover_img" alt="vape_product_advisor" src="<?php echo $this->getSkinUrl('images/vape_product_advisor_hover.png');?>" /> </a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="shopscvapelyfestyles clearfix">
        <div class="shopscvapelyfestyles_title"><span>SHOP</span> CSVAPE LYFESTYLES</div>
        <div class="shopscvapelyfestyles_3part clearfix">
            <div class="shopscvapelyfestyles_3part_holder">
                <div class="shopscvapelyfestyles_3part_inn" style="background-image: url('<?php echo $this->getSkinUrl('images/vgod_dude.jpg');?>');"><img alt="0" src="<?php echo $this->getSkinUrl('images/vgod_tricklyfe.png');?>" />
                    <div class="shopscvapelyfestyles_bottom vgod_tricklyfe"><a href="#">LIVE LYFE</a>
                        <p>Live the VGOD Lyfe with the exclusive Tricklyfe line of products</p>
                    </div>
                </div>
            </div>
            <div class="shopscvapelyfestyles_3part_holder">
                <div class="shopscvapelyfestyles_3part_inn" style="background-image: url('<?php echo $this->getSkinUrl('images/woman_vaping.jpg');?>');"><img alt="0" src="<?php echo $this->getSkinUrl('images/for_her.png');?>" />
                    <div class="shopscvapelyfestyles_bottom woman_vaping"><a href="#">SHOP NOW</a>
                        <p>Live the VGOD Lyfe with the exclusive Tricklyfe line of products</p>
                    </div>
                </div>
            </div>
            <div class="shopscvapelyfestyles_3part_holder">
                <div class="shopscvapelyfestyles_3part_inn" style="background-image: url('<?php echo $this->getSkinUrl('images/gift_ideas.jpg');?>');"><img alt="0" src="<?php echo $this->getSkinUrl('images/gift_ideas_icon.png');?>" />
                    <div class="shopscvapelyfestyles_bottom gift_ideas"><a href="#">SHOP NOW</a>
                        <p>Live the VGOD Lyfe with the exclusive Tricklyfe line of products</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bestkeptsecrets clearfix">
        <div class="bestkeptsecrets_title"><span>BEST</span> KEPT SECRETS</div>
        <div class="bestkeptsecrets_3part clearfix">
            <div class="bestkeptsecrets_3part_holder">
                <div class="bestkeptsecrets_3part_inn wild_cherry_bg" style="background-image: url('<?php echo $this->getSkinUrl('images/wild_cherry.png');?>');"><img alt="0" src="<?php echo $this->getSkinUrl('images/xlvape_logo.png');?>" />
                    <div class="bestkeptsecrets_bottom wild_cherry">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum purus odio, tempor vitae sagittis sit.</p>
                        <a href="#">SHOP NOW</a></div>
                </div>
            </div>
            <div class="bestkeptsecrets_3part_holder">
                <div class="bestkeptsecrets_3part_inn baby_juice_bg" style="background-image: url('<?php echo $this->getSkinUrl('images/baby_juice.png');?>');"><img alt="0" src="<?php echo $this->getSkinUrl('images/juice_man.png');?>" />
                    <div class="bestkeptsecrets_bottom baby_juice">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum purus odio, tempor vitae sagittis sit.</p>
                        <a href="#">SHOP NOW</a></div>
                </div>
            </div>
            <div class="bestkeptsecrets_3part_holder">
                <div class="bestkeptsecrets_3part_inn joyetech_bg" style="background-image: url('<?php echo $this->getSkinUrl('images/joyetech.png');?>');"><img alt="0" src="<?php echo $this->getSkinUrl('images/joyetech_logo.png');?>" />
                    <div class="bestkeptsecrets_bottom joyetech">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum purus odio, tempor vitae sagittis sit.</p>
                        <a href="#">SHOP NOW</a></div>
                </div>
            </div>
        </div>
    </div>
    <div class="loyalltysocialcsvape clearfix">
        <div class="loyalltysocialcsvape_outer">
            <div class="loyalltysocialcsvape_hloder loyalltysocialcsvapeleft_hloder">
                <div class="loyalltysocialcsvape_inn">
                    <h2>CSVAPE <span>LOYALTY</span> PROGRAM</h2>
                    <div class="redmeem_points_reviews_holder">
                        <div class="redmeem_points_reviews">
                            <div class="redmeem_points_reviews_left"><span>REDEEM POINTS</span> for <br /> <span>FREE PRODUCTS</span></div>
                            <div class="redmeem_points_reviews_right">
                                <div class="thumb_up text-center"><a href="#"><img alt="thumb_up" src="<?php echo $this->getSkinUrl('images/thumb_up.png');?>" /></a></div>
                                <div class="reviews_right text-center">&nbsp;</div>
                            </div>
                        </div>
                        <div class="redmeem_points_text">
                            <p>Collect reward points for buying products, sharing your experience on social media, and referring friends and family to the online store you trust most. Things you already do, but you get rewarded for it here. You&rsquo;ll automatically be enrolled into the CSVAPE VIP Rewards Program on your first order.</p>
                            <p>Experience on social media, and referring friends and family to the online store you trust most. Things you already do, but you get rewarded for it here. You&rsquo;ll automatically be enrolled into the CSVAPE VIP Rewards Program on your first order.</p>
                        </div>
                        <div class="redmeem_points_img_but clearfix">
                            <div class="row">
                                <div class="col-xs-6">
                                    <div class="reffer_redeem">
                                        <div class="reffer_redeem_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/reffer.png');?>" /></div>
                                        <div class="reffer_redeem_link"><a href="#">Reffer</a></div>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="reffer_redeem">
                                        <div class="reffer_redeem_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/redeem.png');?>" /></div>
                                        <div class="reffer_redeem_link"><a href="#">Reffer</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="loyalltysocialcsvape_hloder loyalltysocialcsvapemiddle_hloder">
                <div class="loyalltysocialcsvape_inn">
                    <h2>CSVAPE <span>SOCIAL</span> SCENCE</h2>
                    <div class="social_scence_div">
                        <div id="heightdragger">&nbsp;</div>
                        <div id="content-r" class="content">
                            <div class="social_scence_holder">
                                <div class="save_vaping">Support <strong>HR 2058</strong> which could save the vapor industry from total destruction. Info can be found here: <a href="#"><strong>http://casaa.org</strong></a></div>
                                <div class="social_scence_ribbon singleline"><span>SAVE</span> VAPING</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="cs_poll">I used to smoke _______<br /> cigarettes per day before<br /> &nbsp; &nbsp; switching to Vaping.</div>
                                <div class="social_scence_ribbon singleline"><span>CS</span> POLL</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="national_cloud">Follow <strong class="bolder">Vape Capitol&rsquo;</strong>s <br /> <em><strong>Cloud &amp; Tricking Championship</strong></em><br /> Awarding three finalists <strong>$10,000 each.</strong><br /> Infor can be found here:<br /> <a href="http://vapecapitol.com/competitions/my_comp" target="_blank">http://vapecapitol.com/competitions/my_comp</a></div>
                                <div class="social_scence_ribbon"><span>NATIONAL CLOUD</span><br /> AND TRICK COMPETITION</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="save_vaping">Support <strong>HR 2058</strong> which could save the vapor industry from total destruction. Info can be found here: <a href="#"><strong>http://casaa.org</strong></a></div>
                                <div class="social_scence_ribbon singleline"><span>SAVE</span> VAPING</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="cs_poll">I used to smoke _______<br /> cigarettes per day before<br /> &nbsp; &nbsp; switching to Vaping.</div>
                                <div class="social_scence_ribbon singleline"><span>CS</span> POLL</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="national_cloud">Follow <strong class="bolder">Vape Capitol&rsquo;</strong>s <br /> <em><strong>Cloud &amp; Tricking Championship</strong></em><br /> Awarding three finalists <strong>$10,000 each.</strong><br /> Infor can be found here:<br /> <a href="http://vapecapitol.com/competitions/my_comp" target="_blank">http://vapecapitol.com/competitions/my_comp</a></div>
                                <div class="social_scence_ribbon"><span>NATIONAL CLOUD</span><br /> AND TRICK COMPETITION</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="save_vaping">Support <strong>HR 2058</strong> which could save the vapor industry from total destruction. Info can be found here: <a href="#"><strong>http://casaa.org</strong></a></div>
                                <div class="social_scence_ribbon singleline"><span>SAVE</span> VAPING</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="cs_poll">I used to smoke _______<br /> cigarettes per day before<br /> &nbsp; &nbsp; switching to Vaping.</div>
                                <div class="social_scence_ribbon singleline"><span>CS</span> POLL</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="national_cloud">Follow <strong class="bolder">Vape Capitol&rsquo;</strong>s <br /> <em><strong>Cloud &amp; Tricking Championship</strong></em><br /> Awarding three finalists <strong>$10,000 each.</strong><br /> Infor can be found here:<br /> <a href="http://vapecapitol.com/competitions/my_comp" target="_blank">http://vapecapitol.com/competitions/my_comp</a></div>
                                <div class="social_scence_ribbon"><span>NATIONAL CLOUD</span><br /> AND TRICK COMPETITION</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="save_vaping">Support <strong>HR 2058</strong> which could save the vapor industry from total destruction. Info can be found here: <a href="#"><strong>http://casaa.org</strong></a></div>
                                <div class="social_scence_ribbon singleline"><span>SAVE</span> VAPING</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="cs_poll">I used to smoke _______<br /> cigarettes per day before<br /> &nbsp; &nbsp; switching to Vaping.</div>
                                <div class="social_scence_ribbon singleline"><span>CS</span> POLL</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="national_cloud">Follow <strong class="bolder">Vape Capitol&rsquo;</strong>s <br /> <em><strong>Cloud &amp; Tricking Championship</strong></em><br /> Awarding three finalists <strong>$10,000 each.</strong><br /> Infor can be found here:<br /> <a href="http://vapecapitol.com/competitions/my_comp" target="_blank">http://vapecapitol.com/competitions/my_comp</a></div>
                                <div class="social_scence_ribbon"><span>NATIONAL CLOUD</span><br /> AND TRICK COMPETITION</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="save_vaping">Support <strong>HR 2058</strong> which could save the vapor industry from total destruction. Info can be found here: <a href="#"><strong>http://casaa.org</strong></a></div>
                                <div class="social_scence_ribbon singleline"><span>SAVE</span> VAPING</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="cs_poll">I used to smoke _______<br /> cigarettes per day before<br /> &nbsp; &nbsp; switching to Vaping.</div>
                                <div class="social_scence_ribbon singleline"><span>CS</span> POLL</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="national_cloud">Follow <strong class="bolder">Vape Capitol&rsquo;</strong>s <br /> <em><strong>Cloud &amp; Tricking Championship</strong></em><br /> Awarding three finalists <strong>$10,000 each.</strong><br /> Infor can be found here:<br /> <a href="http://vapecapitol.com/competitions/my_comp" target="_blank">http://vapecapitol.com/competitions/my_comp</a></div>
                                <div class="social_scence_ribbon"><span>NATIONAL CLOUD</span><br /> AND TRICK COMPETITION</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="save_vaping">Support <strong>HR 2058</strong> which could save the vapor industry from total destruction. Info can be found here: <a href="#"><strong>http://casaa.org</strong></a></div>
                                <div class="social_scence_ribbon singleline"><span>SAVE</span> VAPING</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="cs_poll">I used to smoke _______<br /> cigarettes per day before<br /> &nbsp; &nbsp; switching to Vaping.</div>
                                <div class="social_scence_ribbon singleline"><span>CS</span> POLL</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="national_cloud">Follow <strong class="bolder">Vape Capitol&rsquo;</strong>s <br /> <em><strong>Cloud &amp; Tricking Championship</strong></em><br /> Awarding three finalists <strong>$10,000 each.</strong><br /> Infor can be found here:<br /> <a href="http://vapecapitol.com/competitions/my_comp" target="_blank">http://vapecapitol.com/competitions/my_comp</a></div>
                                <div class="social_scence_ribbon"><span>NATIONAL CLOUD</span><br /> AND TRICK COMPETITION</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="save_vaping">Support <strong>HR 2058</strong> which could save the vapor industry from total destruction. Info can be found here: <a href="#"><strong>http://casaa.org</strong></a></div>
                                <div class="social_scence_ribbon singleline"><span>SAVE</span> VAPING</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="cs_poll">I used to smoke _______<br /> cigarettes per day before<br /> &nbsp; &nbsp; switching to Vaping.</div>
                                <div class="social_scence_ribbon singleline"><span>CS</span> POLL</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="national_cloud">Follow <strong class="bolder">Vape Capitol&rsquo;</strong>s <br /> <em><strong>Cloud &amp; Tricking Championship</strong></em><br /> Awarding three finalists <strong>$10,000 each.</strong><br /> Infor can be found here:<br /> <a href="http://vapecapitol.com/competitions/my_comp" target="_blank">http://vapecapitol.com/competitions/my_comp</a></div>
                                <div class="social_scence_ribbon"><span>NATIONAL CLOUD</span><br /> AND TRICK COMPETITION</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="save_vaping">Support <strong>HR 2058</strong> which could save the vapor industry from total destruction. Info can be found here: <a href="#"><strong>http://casaa.org</strong></a></div>
                                <div class="social_scence_ribbon singleline"><span>SAVE</span> VAPING</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="cs_poll">I used to smoke _______<br /> cigarettes per day before<br /> &nbsp; &nbsp; switching to Vaping.</div>
                                <div class="social_scence_ribbon singleline"><span>CS</span> POLL</div>
                            </div>
                            <div class="social_scence_holder">
                                <div class="national_cloud">Follow <strong class="bolder">Vape Capitol&rsquo;</strong>s <br /> <em><strong>Cloud &amp; Tricking Championship</strong></em><br /> Awarding three finalists <strong>$10,000 each.</strong><br /> Infor can be found here:<br /> <a href="http://vapecapitol.com/competitions/my_comp" target="_blank">http://vapecapitol.com/competitions/my_comp</a></div>
                                <div class="social_scence_ribbon"><span>NATIONAL CLOUD</span><br /> AND TRICK COMPETITION</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="loyalltysocialcsvape_hloder loyalltysocialcsvaperight_hloder">
                <div class="loyalltysocialcsvape_inn">
                    <h2>WHY BUY FROM <span>CSVAPE?</span></h2>
                    <div class="why_buy_csvape">
                        <div class="why_buy_csvape_holder">
                            <div class="why_buy_csvape_title"><span>PREMIUM</span> QUALITY<br /> <span>PRODUCTS</span></div>
                            <div class="row why_buy_csvape_product">
                                <div class="col-xs-6">
                                    <div class="buy_csvape_product_holder">
                                        <div class="buy_csvape_product_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/e_liquid_product.png');?>" /></div>
                                        <div class="buycsvape_namenumber"><span>350+</span> E-LIQUID FLAVORS</div>
                                        <div class="buycsvape_link"><a href="#">TASTE THEM</a></div>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="buy_csvape_product_holder">
                                        <div class="buy_csvape_product_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/vape_products.png');?>" /></div>
                                        <div class="buycsvape_namenumber"><span>600+</span> VAPE PRODUCTS</div>
                                        <div class="buycsvape_link"><a href="#">GET YOURS</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="why_buy_csvape_holder">
                            <div class="why_buy_csvape_title singleline margintop15"><span>SUPERIOR</span> SERVICE</div>
                            <div class="row why_buy_csvape_product">
                                <div class="col-xs-6">
                                    <div class="buy_csvape_product_holder">
                                        <div class="buy_csvape_product_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/global_customer.png');?>" /></div>
                                        <div class="buycsvape_namenumber"><span>40,000+</span> GLOBAL CUSTOMERS</div>
                                        <div class="buycsvape_link"><a href="#">BECOME ONE</a></div>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="buy_csvape_product_holder">
                                        <div class="buy_csvape_product_img"><img alt="0" src="<?php echo $this->getSkinUrl('images/products_reviews.png');?>" /></div>
                                        <div class="buycsvape_namenumber"><span>5,000+</span> Product reviews</div>
                                        <div class="buycsvape_link"><a href="#">READ THEM</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="specialthanks clearfix">
        <div class="specialthanks_title"><span>SPECIAL THANKS</span> TO OUR PARTNERS</div>
        <div class="specialthanks_2part clearfix">
            <div class="specialthanks_2part_holder">
                <div class="specialthanks_2part_holder_inn">
                    <h4>E-Liquid Brands</h4>
                    <div class="eLiquied_carousel">
                        <div class="eLiquiedBrandProduct-carousel">
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="baked_vapes" src="<?php echo $this->getSkinUrl('images/baked_vapes.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="vgod_thumb" src="<?php echo $this->getSkinUrl('images/vgod_thumb.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="fredericks" src="<?php echo $this->getSkinUrl('images/fredericks.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="vaping_monkey" src="<?php echo $this->getSkinUrl('images/vaping_monkey.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="space_jam" src="<?php echo $this->getSkinUrl('images/space_jam.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="mystic_atmos" src="<?php echo $this->getSkinUrl('images/mystic_atmos.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="tobeco" src="<?php echo $this->getSkinUrl('images/tobeco.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="joyetech_icon" src="<?php echo $this->getSkinUrl('images/joyetech_icon.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="eleaf" src="<?php echo $this->getSkinUrl('images/eleaf.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="sigelei" src="<?php echo $this->getSkinUrl('images/sigelei.png');?>" /></a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="specialthanks_2part_holder">
                <div class="specialthanks_2part_holder_inn">
                    <h4>Product Brands</h4>
                    <div class="eLiquied_carousel">
                        <div class="eLiquiedBrandProduct-carousel">
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="mystic_atmos" src="<?php echo $this->getSkinUrl('images/mystic_atmos.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="tobeco" src="<?php echo $this->getSkinUrl('images/tobeco.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="joyetech_icon" src="<?php echo $this->getSkinUrl('images/joyetech_icon.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="eleaf" src="<?php echo $this->getSkinUrl('images/eleaf.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="sigelei" src="<?php echo $this->getSkinUrl('images/sigelei.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="baked_vapes" src="<?php echo $this->getSkinUrl('images/baked_vapes.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="vgod_thumb" src="<?php echo $this->getSkinUrl('images/vgod_thumb.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="fredericks" src="<?php echo $this->getSkinUrl('images/fredericks.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="vaping_monkey" src="<?php echo $this->getSkinUrl('images/vaping_monkey.png');?>" /></a></div>
                            </div>
                            <div class="item">
                                <div class="top3owl_holder"><a href="#"><img alt="space_jam" src="<?php echo $this->getSkinUrl('images/space_jam.png');?>" /></a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>
