<?php
/*
 * Doc block 
 *
 * 
 *
**/
?>
<?php $_helper = Mage::helper('catalog/category') ?>
<?php $_categories = $_helper->getStoreCategories() ?>
<?php $currentCategory = Mage::registry('current_category') ?>

<div class="left_navigation">
    <div class="left_navigation_holder">
        <nav class="navbar navbar-default">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#leftNav">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="leftNav">
                <div class="nav_holder">
                    <?php if (count($_categories) > 0): ?>
                        <ul class="nav navbar-nav mainnav">
                            <li class="active"><a href="<?php echo Mage::getBaseUrl();?>" class="navigation_icon nav_home"><?php echo $this->__('Home'); ?></a></li>
                            <?php foreach ($_categories as $_category): ?>
                                <?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
                                <?php $_subcategories = $_category->getChildrenCategories() ?>
                                <?php $hasCatLvl2 = count($_subcategories) > 0 ?  1 : 0; ?>
                                <li <?php if ($hasCatLvl2 > 0): ?>class="dropdown"<?php endif; ?>>
                                    <a href="<?php echo $_helper->getCategoryUrl($_category) ?>">
                                        <?php echo $_category->getName() ?>
                                    </a>
                                    
                                    <?php if ($hasCatLvl2 > 0): ?>
                                        <ul>
                                            <?php foreach ($_subcategories as $_subcategory): ?>
                                                <li>
                                                    <a href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>">
                                                        <?php echo $_subcategory->getName() ?>
                                                    </a>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    <?php endif; ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
<!--                    <ul class="nav navbar-nav mainnav">
                        <li class="active"><a href="index.html" class="navigation_icon nav_home">Home</a></li>
                        <li class="dropdown" id="e_liquidsnav">
                            <a href="vape-juice.html" class="navigation_icon nav_e_liquids">
                                E-Juice 
                                <span class="caret_link"><i class="fa fa-angle-right"></i></span>
                            </a> 
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="caret_link"><i class="fa fa-angle-right"></i></span>
                            </a>
                            <div class="dropdown-menu">
                                <div class="dropdown-menu-holder">
                                    <h4><a href="vape-juice.html">E-JUICE</a></h4>
                                    <ul class="menu_1st_lavel">
                                        <li class="menu_1st_lavel_link"><a href="#">E-JUICE FLAVOR TYPES</a>
                                            <ul  class="menu_2nd_lavel_link">
                                                <li><a href="#">Fruity Flavor E-Juice</a></li>
                                                <li><a href="#">Candy Flavor E-Juice</a></li>
                                                <li><a href="#">Drink Flavor E-Juice</a></li>
                                                <li><a href="#">Fruity Flavor E-Juice</a></li>
                                                <li><a href="#">Dessert Flavor E-Juice</a></li>
                                                <li><a href="#">Menthol Flavor E-Juice</a></li>
                                                <li><a href="#">Cafe Flavor E-Juice</a></li>
                                                <li><a href="#">Tobacco Flavor E-Juice</a></li>
                                            </ul>
                                        </li>
                                        <li class="menu_1st_lavel_text"><span>E-JUICE BRANDS</span>
                                            <ul  class="menu_2nd_lavel_text_link">
                                                <li><a href="#">Adam BOMB</a> </li>
                                                <li><a href="#">ANML</a> </li>
                                                <li><a href="#">Broken Bottle</a> </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <li><a href="vape-starter-kits.html" class="navigation_icon nav_straterkit">Vape<br>Starter Kits</a></li>
                        <li><a href="mods.html" class="navigation_icon nav_mods">Mods</a></li>
                        <li><a href="tanks.html" class="navigation_icon nav_tanks">Tanks</a></li>
                        <li><a href="rda.html" class="navigation_icon nav_rda">RDA</a></li>
                        <li class="dropdown" id="e_cig_accessoriesnav"><a href="vape-accessories.html" class="navigation_icon nav_e_cig_accessories">Vape  ACCESSORIES <span class="caret_link"><i class="fa fa-angle-right"></i></span></a> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="caret_link"><i class="fa fa-angle-right"></i></span></a>
                            <div class="dropdown-menu">
                                <div class="dropdown-menu-holder">
                                    <h4><a href="#">Vape Accessories</a></h4>
                                    <ul class="menu_1st_lavel resourcecenterul">
                                        <li class="menu_1st_lavel_link"><a href="#">ATOMIZER REPLACEMENT COILS</a> </li>
                                        <li class="menu_1st_lavel_link"><a href="#">Mod Batteries</a> </li>
                                        <li class="menu_1st_lavel_link"><a href="#">Battery Chargers</a> </li>
                                        <li class="menu_1st_lavel_link"><a href="#">RDA Caps</a> </li>
                                        <li class="menu_1st_lavel_link"><a href="#">Cotton Wicks</a> </li>
                                        <li class="menu_1st_lavel_link"><a href="#">Low Resistance Wires</a> </li>
                                        <li class="menu_1st_lavel_link"><a href="#">Drip Tips</a> </li>
                                        <li class="menu_1st_lavel_link"><a href="#">Carrying Cases</a> </li>
                                        <li class="menu_1st_lavel_link"><a href="#">Holder</a> </li>
                                        <li class="menu_1st_lavel_link"><a href="#">Coil Build Tools</a> </li>
                                        <li class="menu_1st_lavel_link"><a href="#">Apparel</a> </li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <li><a href="#" class="navigation_icon nav_deals">DEALS </a></li>
                        <li><a href="#" class="navigation_icon nav_vgod"></a></li>
                        <li class="dropdown lastdropdown" id="resource_centernav"><a href="resource-center.html" class="navigation_icon nav_resource_center">RESOURCE CENTER <span class="caret_link"><i class="fa fa-angle-right"></i></span></a> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="caret_link"><i class="fa fa-angle-right"></i></span></a>
                            <div class="dropdown-menu">
                                <div class="dropdown-menu-holder">
                                    <h4><a href="#">RESOURCE CENTER</a></h4>
                                    <ul class="menu_1st_lavel resourcecenterul">
                                        <li class="menu_1st_lavel_link"><a href="#">Review</a></li>
                                        <li class="menu_1st_lavel_link"><a href="#">Brand Showroom</a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>-->
                </div>
            </div>
        </nav>
    </div>
</div>